<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>EasyFileExplorer.Operations</RootNamespace>
    <AssemblyName>EasyFileExplorer.Operations</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\FileSystem\FileSystem.csproj" />
  </ItemGroup>
</Project>
